name: Erlang CI

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [lab1]

    defaults:
      run:
        working-directory: ${{matrix.folder}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Erlang
        uses: erlef/setup-beam@v1
        with:
            otp-version: '26.0'
            rebar3-version: '3.24.0'

      - name: Build App
        run: |
          rebar3 compile

      - name: Code formatting erlfmt test
        run: |
          rebar3 fmt --check --verbose

      - name: Run dialyzer
        run: |
          rebar3 dialyzer

      - name: Run elvis
        run: |
          rebar3 lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [lab1]

    defaults:
      run:
        working-directory: ${{matrix.folder}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: '26.0'
          rebar3-version: '3.24.0'

      - name: Build App
        run: |
          rebar3 compile

      - name: Run Eunit tests
        run: |
          rebar3 eunit
        
